name: open-issue
on: 
    issues:
        types:
            - opened

jobs:
    echo_issue:
        runs-on: ubuntu-latest
        steps:
            - name: output event
              run: echo "${{ toJson(github.event) }}"